# Generated by Django 5.2.12 on 2026-03-31 08:37

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='pattern',
            field=models.CharField(blank=True, help_text='Striped, checked, floral, solid, graphic', max_length=50),
        ),
        migrations.AddField(
            model_name='product',
            name='primary_color',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='product',
            name='secondary_colors',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='productimage',
            name='is_front',
            field=models.BooleanField(default=True, help_text='Is this front view?'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['sku'], name='catalog_pro_sku_2c4c34_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['brand'], name='catalog_pro_brand_f6911e_idx'),
        ),
        migrations.AddIndex(
            model_name='productimage',
            index=models.Index(fields=['product', 'is_front'], name='catalog_pro_product_06f1d0_idx'),
        ),
    ]
