# Generated by Django 5.2.12 on 2026-05-09 18:33

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_alter_productimage_image'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='total_sold',
            field=models.IntegerField(db_index=True, default=0, help_text='Total number sold'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['-total_sold'], name='catalog_pro_total_s_2ea6a4_idx'),
        ),
    ]
