# Generated by Django 5.2.12 on 2026-05-10 13:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_product_total_sold_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DealOfTheDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deal_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('original_price_was', models.DecimalField(decimal_places=2, editable=False, max_digits=10)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('is_active', models.BooleanField(default=True)),
                ('display_order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_deals', to='catalog.product')),
                ('wholesaler', models.ForeignKey(limit_choices_to={'role': 'wholesaler'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['display_order', 'start_date'],
                'indexes': [models.Index(fields=['wholesaler', 'is_active'], name='catalog_dea_wholesa_22406a_idx'), models.Index(fields=['start_date', 'end_date'], name='catalog_dea_start_d_c8283a_idx')],
            },
        ),
    ]
