# Generated by Django 5.2.12 on 2026-05-13 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_dealoftheday'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='seller_type',
            field=models.CharField(choices=[('wholesaler', 'Wholesaler'), ('retailer', 'Retailer')], db_index=True, default='wholesaler', max_length=20),
        ),
    ]
