# Generated by Django 5.2.12 on 2026-04-17 06:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_product_retailer_product_wholesaler'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='min_order_qty',
            field=models.IntegerField(default=1, help_text='Minimum quantity per order', validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AddField(
            model_name='product',
            name='retail_price',
            field=models.DecimalField(decimal_places=2, default=0, help_text='MRP for customers', max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
