# Generated by Django 5.2.12 on 2026-05-21 11:25

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_product_catalog_pro_seller__d22880_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='has_discount',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='season',
            field=models.CharField(blank=True, choices=[('summer', 'Summer'), ('winter', 'Winter'), ('festive', 'Festive')], db_index=True, max_length=10, null=True),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['has_discount', 'status'], name='catalog_pro_has_dis_4fd054_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['season', 'status'], name='catalog_pro_season_f252ec_idx'),
        ),
    ]
