# Generated by Django 5.2.12 on 2026-05-21 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_product_has_discount_product_season_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='display_order',
            field=models.IntegerField(db_index=True, default=0),
        ),
    ]
