# Generated by Django 5.2.12 on 2026-04-21 07:06

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0007_product_min_order_qty_product_retail_price'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('user_type', models.CharField(choices=[('wholesaler', 'Wholesaler'), ('retailer', 'Retailer'), ('customer', 'Customer')], default='customer', max_length=20)),
                ('status', models.CharField(choices=[('active', 'Active'), ('abandoned', 'Abandoned'), ('converted', 'Converted to Order')], db_index=True, default='active', max_length=20)),
                ('coupon_code', models.CharField(blank=True, max_length=50)),
                ('coupon_discount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_activity', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='carts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('price_at_add', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('selected_size', models.CharField(blank=True, max_length=50)),
                ('selected_color', models.CharField(blank=True, max_length=50)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='commerce.cart')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cart_items', to='catalog.product')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(db_index=True, max_length=50, unique=True)),
                ('tracking_number', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('discount_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('shipping_charge', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('tax_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('grand_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('pending', 'Pending Payment'), ('confirmed', 'Confirmed'), ('processing', 'Processing'), ('shipped', 'Shipped'), ('out_for_delivery', 'Out for Delivery'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled'), ('refunded', 'Refunded')], db_index=True, default='pending', max_length=20)),
                ('payment_status', models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('failed', 'Failed'), ('refunded', 'Refunded')], db_index=True, default='pending', max_length=20)),
                ('payment_method', models.CharField(max_length=50)),
                ('shipping_name', models.CharField(max_length=255)),
                ('shipping_phone', models.CharField(max_length=20)),
                ('shipping_address', models.TextField()),
                ('shipping_city', models.CharField(max_length=100)),
                ('shipping_state', models.CharField(max_length=100)),
                ('shipping_pincode', models.CharField(db_index=True, max_length=10)),
                ('delivery_type', models.CharField(choices=[('standard', 'Standard (5-7 days)'), ('express', 'Express (2-3 days)')], default='standard', max_length=20)),
                ('expected_delivery_date', models.DateField(blank=True, null=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_orders', to=settings.AUTH_USER_MODEL)),
                ('retailer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='retailer_orders', to=settings.AUTH_USER_MODEL)),
                ('wholesaler', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='wholesaler_orders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(db_index=True, max_length=255)),
                ('product_sku', models.CharField(db_index=True, max_length=100)),
                ('product_image', models.CharField(blank=True, max_length=500)),
                ('quantity', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('seller_id', models.IntegerField(db_index=True)),
                ('seller_name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='commerce.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.product')),
            ],
        ),
        migrations.CreateModel(
            name='StockHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('order', 'Order Placed'), ('cancel', 'Order Cancelled'), ('return', 'Product Returned'), ('restock', 'Restocked'), ('adjust', 'Manual Adjustment')], db_index=True, max_length=20)),
                ('quantity', models.IntegerField()),
                ('old_stock', models.IntegerField()),
                ('new_stock', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='commerce.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_history', to='catalog.product')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='cart',
            index=models.Index(fields=['user', 'status'], name='commerce_ca_user_id_448966_idx'),
        ),
        migrations.AddIndex(
            model_name='cart',
            index=models.Index(fields=['session_id', 'status'], name='commerce_ca_session_08dec0_idx'),
        ),
        migrations.AddIndex(
            model_name='cart',
            index=models.Index(fields=['-last_activity'], name='commerce_ca_last_ac_6d7a3a_idx'),
        ),
        migrations.AddIndex(
            model_name='cartitem',
            index=models.Index(fields=['cart', 'product'], name='commerce_ca_cart_id_58ddd0_idx'),
        ),
        migrations.AddIndex(
            model_name='cartitem',
            index=models.Index(fields=['-added_at'], name='commerce_ca_added_a_2a0297_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='cartitem',
            unique_together={('cart', 'product', 'selected_size', 'selected_color')},
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['customer', 'status'], name='commerce_or_custome_3f09f4_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['retailer', 'status'], name='commerce_or_retaile_0ba560_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['wholesaler', 'status'], name='commerce_or_wholesa_bd598b_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['order_number'], name='commerce_or_order_n_8308f7_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['tracking_number'], name='commerce_or_trackin_0cd177_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['created_at'], name='commerce_or_created_41d89b_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['status', 'payment_status'], name='commerce_or_status_ec3d83_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['shipping_pincode'], name='commerce_or_shippin_babad3_idx'),
        ),
        migrations.AddIndex(
            model_name='orderitem',
            index=models.Index(fields=['order', 'product'], name='commerce_or_order_i_045869_idx'),
        ),
        migrations.AddIndex(
            model_name='orderitem',
            index=models.Index(fields=['product_sku'], name='commerce_or_product_796450_idx'),
        ),
        migrations.AddIndex(
            model_name='orderitem',
            index=models.Index(fields=['seller_id'], name='commerce_or_seller__dc69f1_idx'),
        ),
        migrations.AddIndex(
            model_name='orderitem',
            index=models.Index(fields=['-created_at'], name='commerce_or_created_7e2748_idx'),
        ),
        migrations.AddIndex(
            model_name='stockhistory',
            index=models.Index(fields=['product', '-created_at'], name='commerce_st_product_1067f9_idx'),
        ),
        migrations.AddIndex(
            model_name='stockhistory',
            index=models.Index(fields=['transaction_type', 'created_at'], name='commerce_st_transac_e5da4e_idx'),
        ),
        migrations.AddIndex(
            model_name='stockhistory',
            index=models.Index(fields=['order'], name='commerce_st_order_i_361b3f_idx'),
        ),
    ]
