# Generated by Django 5.2.12 on 2026-04-21 18:12

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_product_min_order_qty_product_retail_price'),
        ('commerce', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('user_type', models.CharField(choices=[('wholesaler', 'Wholesaler'), ('retailer', 'Retailer'), ('customer', 'Customer')], default='customer', max_length=20)),
                ('status', models.CharField(choices=[('active', 'Active'), ('abandoned', 'Abandoned'), ('converted', 'Converted to Order')], db_index=True, default='active', max_length=20)),
                ('coupon_code', models.CharField(blank=True, max_length=50)),
                ('coupon_discount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_activity', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('price_at_add', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('selected_size', models.CharField(blank=True, max_length=50)),
                ('selected_color', models.CharField(blank=True, max_length=50)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='StockHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('order', 'Order Placed'), ('cancel', 'Order Cancelled'), ('return', 'Product Returned'), ('restock', 'Restocked'), ('adjust', 'Manual Adjustment')], db_index=True, max_length=20)),
                ('quantity', models.IntegerField()),
                ('old_stock', models.IntegerField()),
                ('new_stock', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveIndex(
            model_name='order',
            name='commerce_or_custome_9f9817_idx',
        ),
        migrations.RemoveIndex(
            model_name='order',
            name='commerce_or_status_ab9590_idx',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='city',
            new_name='shipping_city',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='state',
            new_name='shipping_state',
        ),
        migrations.RemoveField(
            model_name='order',
            name='pincode',
        ),
        migrations.AddField(
            model_name='order',
            name='delivered_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_type',
            field=models.CharField(choices=[('standard', 'Standard (5-7 days)'), ('express', 'Express (2-3 days)')], default='standard', max_length=20),
        ),
        migrations.AddField(
            model_name='order',
            name='discount_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='order',
            name='expected_delivery_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='grand_total',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='order',
            name='paid_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_charge',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_name',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_phone',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_pincode',
            field=models.CharField(db_index=True, default=1, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='tax_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='order',
            name='tracking_number',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='user_agent',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orderitem',
            name='product_image',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='seller_id',
            field=models.IntegerField(db_index=True, default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orderitem',
            name='seller_name',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_number',
            field=models.CharField(db_index=True, max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('failed', 'Failed'), ('refunded', 'Refunded')], db_index=True, default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='order',
            name='retailer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='retailer_orders', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending Payment'), ('confirmed', 'Confirmed'), ('processing', 'Processing'), ('shipped', 'Shipped'), ('out_for_delivery', 'Out for Delivery'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled'), ('refunded', 'Refunded')], db_index=True, default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='product_name',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='product_sku',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='quantity',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['customer', 'status'], name='commerce_or_custome_3f09f4_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['retailer', 'status'], name='commerce_or_retaile_0ba560_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['wholesaler', 'status'], name='commerce_or_wholesa_bd598b_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['tracking_number'], name='commerce_or_trackin_0cd177_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['created_at'], name='commerce_or_created_41d89b_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['status', 'payment_status'], name='commerce_or_status_ec3d83_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['shipping_pincode'], name='commerce_or_shippin_babad3_idx'),
        ),
        migrations.AddIndex(
            model_name='orderitem',
            index=models.Index(fields=['order', 'product'], name='commerce_or_order_i_045869_idx'),
        ),
        migrations.AddIndex(
            model_name='orderitem',
            index=models.Index(fields=['product_sku'], name='commerce_or_product_796450_idx'),
        ),
        migrations.AddIndex(
            model_name='orderitem',
            index=models.Index(fields=['seller_id'], name='commerce_or_seller__dc69f1_idx'),
        ),
        migrations.AddIndex(
            model_name='orderitem',
            index=models.Index(fields=['-created_at'], name='commerce_or_created_7e2748_idx'),
        ),
        migrations.AddField(
            model_name='cart',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='carts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='cart',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='commerce.cart'),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cart_items', to='catalog.product'),
        ),
        migrations.AddField(
            model_name='stockhistory',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='stockhistory',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='commerce.order'),
        ),
        migrations.AddField(
            model_name='stockhistory',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_history', to='catalog.product'),
        ),
        migrations.AddIndex(
            model_name='cart',
            index=models.Index(fields=['user', 'status'], name='commerce_ca_user_id_448966_idx'),
        ),
        migrations.AddIndex(
            model_name='cart',
            index=models.Index(fields=['session_id', 'status'], name='commerce_ca_session_08dec0_idx'),
        ),
        migrations.AddIndex(
            model_name='cart',
            index=models.Index(fields=['-last_activity'], name='commerce_ca_last_ac_6d7a3a_idx'),
        ),
        migrations.AddIndex(
            model_name='cartitem',
            index=models.Index(fields=['cart', 'product'], name='commerce_ca_cart_id_58ddd0_idx'),
        ),
        migrations.AddIndex(
            model_name='cartitem',
            index=models.Index(fields=['-added_at'], name='commerce_ca_added_a_2a0297_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='cartitem',
            unique_together={('cart', 'product', 'selected_size', 'selected_color')},
        ),
        migrations.AddIndex(
            model_name='stockhistory',
            index=models.Index(fields=['product', '-created_at'], name='commerce_st_product_1067f9_idx'),
        ),
        migrations.AddIndex(
            model_name='stockhistory',
            index=models.Index(fields=['transaction_type', 'created_at'], name='commerce_st_transac_e5da4e_idx'),
        ),
        migrations.AddIndex(
            model_name='stockhistory',
            index=models.Index(fields=['order'], name='commerce_st_order_i_361b3f_idx'),
        ),
    ]
