# Generated by Django 5.2.12 on 2026-05-24 16:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReturnRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('return_number', models.CharField(db_index=True, max_length=50, unique=True)),
                ('return_type', models.CharField(choices=[('return', 'Return'), ('exchange', 'Exchange')], default='return', max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('completed', 'Completed')], default='pending', max_length=20)),
                ('reason', models.TextField()),
                ('comments', models.TextField(blank=True)),
                ('items', models.JSONField(default=list)),
                ('refund_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('images', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_returns', to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='return_requests', to='commerce.order')),
                ('retailer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='retailer_returns', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['return_number'], name='commerce_re_return__2a1fb5_idx'), models.Index(fields=['status'], name='commerce_re_status_56414f_idx'), models.Index(fields=['retailer', 'status'], name='commerce_re_retaile_c361c6_idx'), models.Index(fields=['order'], name='commerce_re_order_i_763aa8_idx')],
            },
        ),
    ]
