# Generated by Django 5.2.12 on 2026-04-23 16:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0002_cart_cartitem_stockhistory_alter_order_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='user_type',
            field=models.CharField(choices=[('wholesaler', 'Wholesaler'), ('retailer', 'Retailer'), ('customer', 'Customer'), ('support', 'Support Staff'), ('admin', 'Admin')], default='customer', max_length=20),
        ),
        migrations.CreateModel(
            name='OrderStatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='commerce.order')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['order', '-created_at'], name='commerce_or_order_i_999997_idx')],
            },
        ),
    ]
