# Generated by Django 5.2.12 on 2026-05-26 06:51

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0009_category_display_order'),
        ('commerce', '0003_returnrequest'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LoyaltySettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points_per_rupee', models.DecimalField(decimal_places=2, default=1.0, max_digits=5)),
                ('min_redemption_points', models.IntegerField(default=100)),
                ('max_redemption_points', models.IntegerField(default=5000)),
                ('points_expiry_months', models.IntegerField(default=6)),
                ('welcome_bonus_points', models.IntegerField(default=50)),
                ('birthday_bonus_points', models.IntegerField(default=100)),
                ('referral_bonus_points', models.IntegerField(default=200)),
                ('bronze_threshold', models.IntegerField(default=0)),
                ('silver_threshold', models.IntegerField(default=10000)),
                ('gold_threshold', models.IntegerField(default=25000)),
                ('platinum_threshold', models.IntegerField(default=50000)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Loyalty Settings',
            },
        ),
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('campaign_type', models.CharField(choices=[('bonus', 'Bonus Points'), ('birthday', 'Birthday Bonus'), ('referral', 'Referral Bonus'), ('welcome', 'Welcome Bonus'), ('festival', 'Festival Special')], db_index=True, max_length=20)),
                ('bonus_points', models.IntegerField()),
                ('description', models.TextField(blank=True)),
                ('eligible_tiers', models.JSONField(blank=True, default=list)),
                ('min_order_value', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('start_date', models.DateTimeField(db_index=True)),
                ('end_date', models.DateTimeField(db_index=True)),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('active', 'Active'), ('expired', 'Expired'), ('cancelled', 'Cancelled')], db_index=True, default='scheduled', max_length=20)),
                ('total_redeemed', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', 'start_date', 'end_date'], name='commerce_ca_status_62ee86_idx'), models.Index(fields=['campaign_type', 'status'], name='commerce_ca_campaig_509519_idx')],
            },
        ),
        migrations.CreateModel(
            name='Reward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('discount', 'Discount Coupon'), ('shipping', 'Free Shipping'), ('gift', 'Gift Card'), ('product', 'Free Product'), ('access', 'Early Access')], db_index=True, max_length=20)),
                ('points_required', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('description', models.TextField()),
                ('value', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('image_url', models.URLField(blank=True)),
                ('icon', models.CharField(blank=True, max_length=50)),
                ('stock', models.IntegerField(default=999, help_text='Remaining quantity, -1 for unlimited')),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('is_popular', models.BooleanField(default=False)),
                ('total_redeemed', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['points_required'],
                'indexes': [models.Index(fields=['category', 'is_active'], name='commerce_re_categor_940ab7_idx'), models.Index(fields=['points_required'], name='commerce_re_points__e5a0a2_idx')],
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(choices=[(1, '1 Star - Poor'), (2, '2 Stars - Fair'), (3, '3 Stars - Good'), (4, '4 Stars - Very Good'), (5, '5 Stars - Excellent')])),
                ('title', models.CharField(max_length=200)),
                ('comment', models.TextField()),
                ('images', models.JSONField(blank=True, default=list)),
                ('is_verified_purchase', models.BooleanField(default=False)),
                ('is_approved', models.BooleanField(default=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('helpful_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='commerce.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='catalog.product')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['product', '-created_at'], name='commerce_re_product_f10af3_idx'), models.Index(fields=['customer', '-created_at'], name='commerce_re_custome_891ebc_idx'), models.Index(fields=['rating'], name='commerce_re_rating_340a5a_idx'), models.Index(fields=['is_approved'], name='commerce_re_is_appr_f20a74_idx')],
                'unique_together': {('product', 'customer')},
            },
        ),
        migrations.CreateModel(
            name='PointsTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.CharField(db_index=True, max_length=50, unique=True)),
                ('transaction_type', models.CharField(choices=[('earned', 'Earned from Purchase'), ('redeemed', 'Redeemed for Reward'), ('expired', 'Expired Points'), ('bonus', 'Bonus Points'), ('adjusted', 'Manual Adjustment')], db_index=True, max_length=20)),
                ('points', models.IntegerField()),
                ('balance_after', models.IntegerField()),
                ('description', models.CharField(max_length=255)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='points_transactions', to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='points_transactions', to='commerce.order')),
                ('retailer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='retailer_points_transactions', to=settings.AUTH_USER_MODEL)),
                ('reward', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='points_transactions', to='commerce.reward')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['customer', '-created_at'], name='commerce_po_custome_2e0a30_idx'), models.Index(fields=['transaction_type', 'created_at'], name='commerce_po_transac_b6537b_idx'), models.Index(fields=['expires_at'], name='commerce_po_expires_a68afa_idx')],
            },
        ),
    ]
