# Generated by Django 5.2.12 on 2026-04-24 09:52

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0003_alter_cart_user_type_orderstatushistory'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['wholesaler', 'status', 'created_at'], name='commerce_or_wholesa_2a17c6_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['wholesaler', 'status', '-created_at'], name='commerce_or_wholesa_da92f2_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['created_at', 'status'], name='commerce_or_created_dbc2b4_idx'),
        ),
    ]
