# Generated by Django 5.2.12 on 2026-05-24 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('identity', '0002_user_anniversary_date_user_date_of_birth'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerprofile',
            name='anniversary_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customerprofile',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
    ]
