# Generated by Django 5.2.12 on 2026-04-22 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('identity', '0003_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('wholesaler', 'Wholesaler'), ('retailer', 'Retailer'), ('customer', 'Customer'), ('support', 'Support Staff'), ('admin', 'Admin')], max_length=20),
        ),
    ]
