# Generated by Django 5.2.12 on 2026-04-23 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('identity', '0004_alter_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='wholesalerprofile',
            name='is_verified',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddIndex(
            model_name='wholesalerprofile',
            index=models.Index(fields=['is_verified', 'city'], name='identity_wh_is_veri_5fce24_idx'),
        ),
    ]
