# Generated by Django 5.2.12 on 2026-05-27 17:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GSTReturn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', models.CharField(help_text='e.g., Q1 2026, Jan-Mar 2026', max_length=20)),
                ('tax_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('filed', 'Filed'), ('overdue', 'Overdue')], db_index=True, default='pending', max_length=10)),
                ('filed_date', models.DateField(blank=True, null=True)),
                ('due_date', models.DateField()),
                ('reference_number', models.CharField(blank=True, max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('retailer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gst_returns', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-period'],
                'indexes': [models.Index(fields=['retailer', 'status'], name='analytics_e_retaile_4f8a15_idx'), models.Index(fields=['period'], name='analytics_e_period_25a0e6_idx')],
            },
        ),
    ]
